//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "apps")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(unique)]
    pub app_id: String,
    pub website_url: Option<String>,
    pub app_vername: String,
    pub app_vercode: i32,
    pub app_download_url: String,
    pub app_res_url: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub app_update_info: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub manifest_extra: Json,
    pub code_type: i16,
    pub app_valid_key: String,
    pub trial_days: i32,
    pub trial_num: i32,
    pub sort_order: i32,
    pub status: i16,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::app_devices::Entity")]
    AppDevices,
    #[sea_orm(has_many = "super::license_plans::Entity")]
    LicensePlans,
    #[sea_orm(has_many = "super::orders::Entity")]
    Orders,
    #[sea_orm(has_many = "super::reg_codes::Entity")]
    RegCodes,
}

impl Related<super::app_devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppDevices.def()
    }
}

impl Related<super::license_plans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LicensePlans.def()
    }
}

impl Related<super::orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<super::reg_codes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RegCodes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
