//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod app_devices;
pub mod apps;
pub mod license_plans;
pub mod order_events;
pub mod orders;
pub mod permissions;
pub mod payment_channels;
pub mod reg_codes;
pub mod role_permissions;
pub mod roles;
pub mod system_settings;
pub mod user_roles;
pub mod use_records;
pub mod users;
