//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod app_devices;
pub mod apps;
pub mod permissions;
pub mod reg_codes;
pub mod role_permissions;
pub mod roles;
pub mod user_roles;
pub mod users;
