//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub username: String,
    #[serde(skip_serializing)]
    pub password: String,
    #[sea_orm(unique)]
    pub referral_code: String,
    pub commission_rate_bps: Option<i32>,
    #[serde(skip_serializing)]
    pub settlement_account: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::distribution_commission_adjustments::Entity")]
    DistributionCommissionAdjustments,
    #[sea_orm(has_many = "super::distribution_commissions::Entity")]
    DistributionCommissions,
    #[sea_orm(has_many = "super::distribution_settlement_proofs::Entity")]
    DistributionSettlementProofs,
    #[sea_orm(has_many = "super::distribution_settlements::Entity")]
    DistributionSettlements,
    #[sea_orm(has_many = "super::order_refunds::Entity")]
    OrderRefunds,
    #[sea_orm(has_many = "super::orders::Entity")]
    Orders,
    #[sea_orm(has_many = "super::user_roles::Entity")]
    UserRoles,
}

impl Related<super::distribution_commission_adjustments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DistributionCommissionAdjustments.def()
    }
}

impl Related<super::distribution_commissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DistributionCommissions.def()
    }
}

impl Related<super::distribution_settlement_proofs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DistributionSettlementProofs.def()
    }
}

impl Related<super::distribution_settlements::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DistributionSettlements.def()
    }
}

impl Related<super::order_refunds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrderRefunds.def()
    }
}

impl Related<super::user_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRoles.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_roles::Relation::Roles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_roles::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn serialized_user_omits_password() {
        let now = chrono::Utc::now().fixed_offset();
        let user = Model {
            id: 1,
            username: "admin".to_string(),
            password: "bcrypt-hash".to_string(),
            referral_code: "LHREFERRAL".to_string(),
            commission_rate_bps: None,
            settlement_account: None,
            created_at: now,
            updated_at: now,
        };

        let value = serde_json::to_value(user).unwrap();

        assert!(value.get("password").is_none());
        assert_eq!(value["username"], "admin");
    }
}
