[package]
name = "entities"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = "1.1.13"
serde = { version = "1.0", features = ["derive"] }
rust_decimal = { version = "1.33.1", features = ["serde-with-float"] }
utoipa = { version = "5.0.0", features = ["axum_extras", "chrono"] } 