export enum RouteName {
    Home = 'home',
    Products = 'products',
    AppProducts = 'app_products',
    OrderQuery = 'order_query',
    PayResult = 'pay_result',
    Login = 'login',
    Register = 'register',
    Admin = 'admin',
    AdminDashboard = 'dashboard',
    AdminProducts = 'admin_products',
    AdminOrders = 'orders',
    AdminUsers = 'users',
    AdminRoles = 'roles',
    AdminApps = 'apps',
    AdminResources = 'resources',
    AdminRegCodes = 'reg_codes',
    AdminRegTest = 'reg_test',
    AdminUseRecords = 'use_records',
    AdminDevices = 'devices',
    AdminPermissions = 'permissions',
}


export enum RoutePath {
    Home = '/',
    Products = '/' + RouteName.Products,
    OrderQuery = '/orders/query',
    PayResult = '/pay/result',
    Login = '/' + RouteName.Login,
    Register = '/' + RouteName.Register,
    Admin = '/' + RouteName.Admin,
    AdminDashboard = '/' + RouteName.Admin + '/' + RouteName.AdminDashboard,
    AdminProducts = '/' + RouteName.Admin + '/products',
    AdminOrders = '/' + RouteName.Admin + '/' + RouteName.AdminOrders,
    AdminUsers = '/' + RouteName.Admin + '/' + RouteName.AdminUsers,
    AdminRoles = '/' + RouteName.Admin + '/' + RouteName.AdminRoles,
    AdminApps = '/' + RouteName.Admin + '/' + RouteName.AdminApps,
    AdminResources = '/' + RouteName.Admin + '/' + RouteName.AdminResources,
    AdminRegCodes = '/' + RouteName.Admin + '/' + RouteName.AdminRegCodes,
    AdminRegTest = '/' + RouteName.Admin + '/' + RouteName.AdminRegTest,
    AdminUseRecords = '/' + RouteName.Admin + '/' + RouteName.AdminUseRecords,
    AdminDevices = '/' + RouteName.Admin + '/' + RouteName.AdminDevices,
    AdminPermissions = '/' + RouteName.Admin + '/' + RouteName.AdminPermissions,
}
